services:

  mysql:
    image: mysql:8.4
    container_name: employee-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employee_db
      MYSQL_USER: employee_user
      MYSQL_PASSWORD: employee_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  employee-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: employee_db
      DB_USERNAME: employee_user
      DB_PASSWORD: employee_password
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data: