apiVersion: v1
kind: Service
metadata:
  name: employee-api-service
spec:
  selector:
    io.kompose.service: employee-api

  type: LoadBalancer

  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080