apiVersion: v1
kind: Service
metadata:
  name: employee-api-service
  labels:
    io.kompose.service: employee-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    io.kompose.service: employee-api
