apiVersion: batch/v1
kind: Job

metadata:
  name: employee-data-import

spec:
  backoffLimit: 3

  template:
    metadata:
      labels:
        app: employee-data-import

    spec:
      restartPolicy: Never

      containers:
        - name: mysql-client
          image: mysql:8.4

          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for MySQL..."

              until mysqladmin ping \
                -h mysql \
                -u"$DB_USERNAME" \
                -p"$DB_PASSWORD" \
                --silent
              do
                echo "MySQL is not ready..."
                sleep 5
              done

              echo "MySQL is ready."

              echo "Importing employee_data.sql..."

              mysql \
                -h mysql \
                -u"$DB_USERNAME" \
                -p"$DB_PASSWORD" \
                "$DB_NAME" < /sql/employee_data.sql

              echo "SQL import completed."

              echo "Verifying employee table..."

              mysql \
                -h mysql \
                -u"$DB_USERNAME" \
                -p"$DB_PASSWORD" \
                "$DB_NAME" \
                -e "SELECT * FROM employee;"

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: employee-db-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: employee-db-secret
                  key: DB_PASSWORD

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: employee-db-secret
                  key: DB_NAME

          volumeMounts:
            - name: sql-file
              mountPath: /sql

      volumes:
        - name: sql-file
          configMap:
            name: employee-data-sql